[package]
name = "balaur_ui"
description = "Balaur UI plugin: an immediate-mode egui API for scripts"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
balaur_core.workspace = true
balaur_plugin.workspace = true
egui.workspace = true
anyhow.workspace = true
toml.workspace = true
serde.workspace = true
balaur_script.workspace = true
tracing.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }

[dev-dependencies]
balaur.workspace = true
tempfile = "3"
egui.workspace = true

[lints]
workspace = true
