[package]
name = "balaur_plugin"
description = "What a module or an extension implements to register itself with the engine"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
balaur_core.workspace = true
balaur_script.workspace = true
anyhow.workspace = true

[dev-dependencies]
balaur_script.workspace = true

[lints]
workspace = true
