#!/usr/bin/env python3
"""Regenerate docs/generated/ from the workspace and a booted engine.

Hand-written docs go stale. These are derived, and CI runs --check, so they
are correct or the build is red.
"""
import argparse
import html
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "generated"
BANNER = "<!-- Generated by scripts/gen_docs.py. Do not edit; run `python3 scripts/gen_docs.py`. -->\n\n"


def run(*args):
    """Run a command, and on failure say what it printed.

    Without this the traceback shows only the exit code, which is useless when
    the interesting part is a compiler error thirty lines into stderr.
    """
    p = subprocess.run(args, cwd=ROOT, capture_output=True, text=True, check=False)
    if p.returncode != 0:
        print(f"command failed ({p.returncode}): {' '.join(args)}", file=sys.stderr)
        for stream, text in (("stdout", p.stdout), ("stderr", p.stderr)):
            if text.strip():
                print(f"--- {stream} ---\n{text.rstrip()}", file=sys.stderr)
        raise SystemExit(1)
    return p.stdout


def workspace():
    meta = json.loads(run("cargo", "metadata", "--no-deps", "--format-version", "1"))
    crates = {}
    for pkg in meta["packages"]:
        src = Path(pkg["manifest_path"]).parent
        crates[pkg["name"]] = {
            "description": pkg.get("description") or "",
            "deps": sorted(
                d["name"] for d in pkg["dependencies"]
                if d["name"].startswith("balaur") and d["kind"] is None
            ),
            "dev_deps": sorted(
                d["name"] for d in pkg["dependencies"]
                if d["name"].startswith("balaur") and d["kind"] == "dev"
            ),
            "external": sorted(
                d["name"] for d in pkg["dependencies"]
                if not d["name"].startswith("balaur") and d["kind"] is None
            ),
            "purpose": module_doc(src / "src" / "lib.rs") or module_doc(src / "src" / "main.rs"),
            "dir": src,
        }
    return dict(sorted(crates.items()))


def module_doc(path):
    """The leading //! block, as one paragraph."""
    if not path.exists():
        return ""
    lines = []
    for line in path.read_text().splitlines():
        if line.startswith("//!"):
            lines.append(line[3:].strip())
        elif lines:
            break
    while lines and not lines[-1]:
        lines.pop()
    para = []
    for line in lines:
        if not line:
            break
        para.append(line)
    return " ".join(para)


def public_surface(crate):
    """Count public items, and name the traits and types a crate owns."""
    kinds = {"fn": [], "struct": [], "enum": [], "trait": [], "const": [], "type": []}
    for rs in sorted((crate["dir"] / "src").rglob("*.rs")):
        for m in re.finditer(
            r"^pub (?:async )?(?:unsafe )?(fn|struct|enum|trait|const|type) ([A-Za-z_][A-Za-z0-9_]*)",
            rs.read_text(), re.M,
        ):
            kinds[m.group(1)].append(m.group(2))
    return {k: sorted(set(v)) for k, v in kinds.items()}


def script_api():
    # `apple` is on so the store modules reach the reference: the plugin
    # registers the same functions on every platform, and off an Apple one
    # they answer `unsupported`.
    out = run(
        "cargo", "run", "-q", "-p", "balaur_cli", "--bin", "balaur",
        "--features", "apple", "--", "api",
    )
    return json.loads(out)


def module_owners():
    """Which crate declares each script module, so backend-only ones show up."""
    owners = {}
    for rs in sorted((ROOT / "crates").rglob("src/**/*.rs")):
        crate = rs.relative_to(ROOT / "crates").parts[0]
        for m in re.finditer(r'(?:script_module|module)\(\s*(?:[^,()]+,\s*)*"([a-z0-9_]+)"\s*\)', rs.read_text()):
            owners.setdefault(m.group(1), crate)
    return owners


def test_names():
    """Every test, as a sentence. An undocumented flow is an untested one."""
    out = run("cargo", "test", "--workspace", "--", "--list")
    # Split off the trailing ": test", not the first colon: a name like
    # `det::tests::a_flow` would otherwise be reported as the module `det`.
    paths = [line.rsplit(":", 1)[0] for line in out.splitlines() if line.endswith(": test")]
    return sorted({p.rsplit("::", 1)[-1] for p in paths})


def write(name, body):
    (OUT / name).write_text(BANNER + body)


def gen_crates(crates):
    body = "# Crates\n\nOne section per workspace crate: what it is for, what it\ndepends on inside the workspace, and what it exports.\n\n"
    for name, c in crates.items():
        body += f"## `{name}`\n\n"
        if c["description"]:
            body += f"{c['description']}\n\n"
        if c["purpose"]:
            body += f"{c['purpose']}\n\n"
        body += f"- **workspace deps:** {', '.join(f'`{d}`' for d in c['deps']) or 'none'}\n"
        ext = c["external"]
        body += f"- **external deps:** {len(ext)}"
        if ext:
            body += f" ({', '.join(ext[:8])}{', …' if len(ext) > 8 else ''})"
        body += "\n"
        s = public_surface(c)
        counts = ", ".join(f"{len(v)} {k}" for k, v in s.items() if v) or "nothing public"
        body += f"- **public surface:** {counts}\n"
        for kind in ("trait", "struct", "enum"):
            if s[kind]:
                body += f"- **{kind}s:** {', '.join(f'`{n}`' for n in s[kind])}\n"
        body += "\n"
    return body


def gen_graph(crates):
    body = "# Crate graph\n\nWorkspace dependencies only. Backends depend on core; core never\ndepends on a backend, which is what keeps it language-free.\n\n```mermaid\ngraph TD\n"
    for name, c in crates.items():
        body += f"  {name}[{name}]\n"
    for name, c in crates.items():
        for d in c["deps"]:
            body += f"  {name} --> {d}\n"
    body += "```\n"
    return body


def gen_script_api(api, owners):
    body = "# Script API\n\nEvery module, function and constant a script can reach. Read from a booted\nengine rather than the source, so derived constants are included and this\ncannot drift from what scripts actually see.\n\n"
    backend_only = {m: o for m, o in owners.items() if o.startswith("balaur_script_")}
    body += "| Module | Functions | Constants | Declared by |\n| --- | ---: | ---: | --- |\n"
    for m in api["modules"]:
        where = "the backend" if m["name"] in backend_only else "the engine"
        body += f"| [`{m['name']}`](#{m['name']}) | {len(m['functions'])} | {len(m['constants'])} | {where} |\n"
    body += "\n"
    for m in api["modules"]:
        body += f"## `{m['name']}`\n\n"
        if m["name"] in backend_only:
            body += f"Declared by `{backend_only[m['name']]}`, so it exists only on that backend.\n\n"
        if m["functions"]:
            body += "**Functions:** " + ", ".join(f"`{f}`" for f in m["functions"]) + "\n\n"
        if m["constants"]:
            body += f"**Constants** ({len(m['constants'])}):\n\n"
            shown = m["constants"][:24]
            body += "| Name | Value |\n| --- | --- |\n"
            for c in shown:
                body += f"| `{c['name']}` | `{c['value']}` |\n"
            if len(m["constants"]) > len(shown):
                body += f"\n…and {len(m['constants']) - len(shown)} more.\n"
            body += "\n"
    return body


def component_row(prop, spec):
    """One <tr>. HTML rather than a markdown table because a cell holds
    several sentences with inline code."""
    notes = [html.escape(spec.get("description", ""))]
    if "options" in spec:
        notes.append("One of " + ", ".join(f"<code>{html.escape(o)}</code>" for o in spec["options"]) + ".")
    if "min" in spec or "max" in spec:
        low, high = spec.get("min", ""), spec.get("max", "")
        notes.append(f"Range {low}–{high}." if high != "" else f"At least {low}.")
    if spec.get("shorthand"):
        notes.append(f"Scene shorthand: <code>{html.escape(prop)}</code>'s value can be given as the component's whole value.")
    if spec.get("readonly"):
        notes.append("Read-only: engine output the inspector shows but never writes.")
    kind = spec.get("type", "")
    if kind == "asset":
        kind = f"asset · <code>{html.escape(spec.get('asset', ''))}</code>"
    else:
        kind = html.escape(kind)
    default = json.dumps(spec.get("default", "")).strip('"')
    cells = (
        f"<code>{html.escape(prop)}</code>",
        kind,
        f"<code>{html.escape(default)}</code>" if default else "—",
        " ".join(n for n in notes if n),
    )
    return "<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>"


# Section order for the component reference. A component lands in the first
# group whose tag it carries and lists every tag under its heading.
COMPONENT_GROUPS = [
    ("2d", "2D"),
    ("3d", "3D"),
    ("physics", "Physics"),
    ("render", "Rendering"),
    ("animation", "Animation"),
    ("audio", "Audio"),
    ("ui", "UI"),
]


def component_group(tags):
    for tag, label in COMPONENT_GROUPS:
        if tag in tags:
            return label
    return "Other"


def component_methods(api):
    """`component -> [(module, function, signature, doc)]`.

    Read from what each binding declared it acts on, which is the same
    declaration the script backend turns into `node.<component>.<method>`.
    """
    out = {}
    for module in api.get("modules", []):
        for function, components in (module.get("acts_on") or {}).items():
            for component in components:
                out.setdefault(component, []).append(
                    (
                        module["name"],
                        function,
                        module.get("signatures", {}).get(function, ""),
                        module.get("docs", {}).get(function, ""),
                    )
                )
    for rows in out.values():
        rows.sort(key=lambda row: row[1])
    return out


def bound_signature(signature):
    """The signature as the handle takes it: the node is already bound."""
    for prefix, rest in (("(NodeId, ", "("), ("(NodeId)", "()")):
        if signature.startswith(prefix):
            return rest + signature[len(prefix) :]
    return signature


def method_row(module, function, signature, doc):
    call = f"{html.escape(function)}{html.escape(bound_signature(signature).split(' -> ')[0])}"
    returns = bound_signature(signature).split(" -> ")
    gives = html.escape(returns[1]) if len(returns) > 1 else ""
    cells = (
        f"<code>{call}</code>",
        f"<code>{gives}</code>" if gives and gives != "()" else "—",
        html.escape(doc),
        f"<code>{html.escape(module)}</code>",
    )
    return "<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>"


def gen_components(components, tags, docs=None, methods=None):
    out = [
        "# Components\n\n",
        "Balaur has no node classes and no inheritance tree: every node is the\n"
        "same entity, and capability comes from the components on it.\n\n"
        "In the terms other engines use: a specialized node type there (a\n"
        "`RigidBody2D`, a `Sprite2D`, a `Label`) is here a plain node plus a\n"
        "component, and a content resource there (an animation library, say)\n"
        "is here an [asset](./assets.md), referenced from an `asset`-typed\n"
        "property or defined inline in the scene. Some things that are\n"
        "resources elsewhere are neither here: a collider's shape is plain\n"
        "data on the `collider` component itself. And similar component names\n"
        "are siblings by convention, never inheritance — `body2d` shares\n"
        "nothing with `body`; each component is independent and complete.\n\n"
        "Each component is registered by a plugin with the schema below; one\n"
        "registration provides the scene-file key, the runtime\n"
        "`node:set_component` family, and the editor's inspector rows.\n\n"
        "**Methods.** `node.<component>` is a handle that binds the node to the\n"
        "module driving that component, so `node.body2d.apply_impulse(1.0, 0.0)`\n"
        "is `physics2d::apply_impulse(node, 1.0, 0.0)` and the same call on a\n"
        "`body3d` handle reaches `physics3d`. The methods listed per component\n"
        "below are the functions that declared they act on it. Every handle also\n"
        "carries `get()`, `set(table)`, `has()` and `remove()`, so a component\n"
        "with no methods of its own is still reachable that way.\n\n"
        "Components are grouped by the first of their facet tags; one with\n"
        "several (`collider2d` is both `2d` and `physics`) lists them all under\n"
        "its heading.\n\n",
    ]
    groups = {}
    for name in sorted(components):
        groups.setdefault(component_group(tags.get(name, [])), []).append(name)
    for label in [label for _, label in COMPONENT_GROUPS] + ["Other"]:
        if label not in groups:
            continue
        out.append(f"## {label}\n\n")
        for name in groups[label]:
            schema = components[name]
            props = sorted(schema)
            rows = "\n".join(component_row(p, schema[p]) for p in props)
            facets = " · ".join(f"`{t}`" for t in tags.get(name, [])) or "untagged"
            summary = (docs or {}).get(name, "")
            calls = (methods or {}).get(name, [])
            count = f"{len(props)} propert{'y' if len(props) == 1 else 'ies'}"
            if calls:
                count += f" · {len(calls)} method{'' if len(calls) == 1 else 's'}"
            out.append(
                f"### `{name}`\n\n"
                f"{facets} · {count}\n\n"
                + (f"{summary}\n\n" if summary else "")
                + "<table>\n<thead><tr><th>property</th><th>type</th><th>default</th>"
                f"<th>description</th></tr></thead>\n<tbody>\n{rows}\n</tbody>\n</table>\n\n"
            )
            if calls:
                body = "\n".join(method_row(*call) for call in calls)
                out.append(
                    f"On a node carrying `{name}`, as `node.{name}.<method>`:\n\n"
                    "<table>\n<thead><tr><th>method</th><th>gives</th>"
                    "<th>description</th><th>module</th></tr></thead>\n"
                    f"<tbody>\n{body}\n</tbody>\n</table>\n\n"
                )
    return "".join(out)


def asset_users(components):
    """`component.property` per asset type, read off the component schemas."""
    users = {}
    for component in sorted(components):
        for prop, spec in sorted(components[component].items()):
            if spec.get("type") == "asset":
                users.setdefault(spec.get("asset", ""), []).append(f"`{component}.{prop}`")
    return users


def gen_assets(asset_types, functions, components):
    """The asset reference: what an asset is, and every type plugins register."""
    out = [
        "# Assets\n\n",
        "An asset is game content several nodes share, or that is too big to\n"
        "inline in a scene node. This is what Godot calls a Resource.\n\n"
        "Content lives in files (or inline in a scene) rather than on a node,\n"
        "and plugins register asset types the same way they register\n"
        "components. An `asset`-typed component property names which type it\n"
        "takes, which is also what gives it an inspector row.\n\n"
        "## One rule\n\n"
        "**A string is a reference, a table is a definition.** Every\n"
        "asset-typed property accepts either:\n\n"
        "```toml\n"
        "[nodes.animation]\n"
        "library = \"animations/platform.toml\"   # a reference: every node naming it shares one parsed asset\n\n"
        "# or, inline:\n"
        "[nodes.animation.library]\n"
        "type = \"animation_clip\"\n"
        "# ... the definition, written in place\n"
        "```\n\n"
        "An author writes three reference forms and no more:\n\n"
        "| Form | Meaning |\n| --- | --- |\n"
        "| `\"animations/hero.toml\"` | The whole file |\n"
        "| `\"animations/hero.toml#run\"` | The entry named `run` inside it |\n"
        "| `\"#hero_idle\"` | An `[[assets]]` block in the same scene document |\n\n"
        "Sharing is the default; `assets.duplicate` opts out with a private\n"
        "copy. A reference that does not resolve warns and the rest of the\n"
        "scene loads, so one bad path does not take a whole scene down. A\n"
        "definition table that does not parse is an error, reported where it\n"
        "was written.\n\n"
        "## Types\n\n"
        "Registered by plugins, so this list is whatever the build contains.\n"
        "Each type says where its files live, which component properties take\n"
        "it, and what a definition table holds.\n\n",
    ]
    users = asset_users(components)
    for name in sorted(asset_types):
        info = asset_types[name]
        directory = info.get("directory", "")
        home = f"`{directory}/`" if directory else "none, so it cannot be promoted to a file"
        used = ", ".join(users.get(name, [])) or "no component property yet"
        out.append(f"### `{name}`\n\nFiles: {home}. Used by: {used}.\n\n")
        doc = info.get("doc", "").strip()
        if doc:
            out.append(doc + "\n\n")
    if functions:
        listed = ", ".join(f"`{f}`" for f in sorted(functions))
        out.append(
            "\n## The `assets` script module\n\n"
            f"{listed}.\n\n"
        )
    out.append(
        "## Plugins define asset types\n\n"
        "Core never learns what an asset *is*. A plugin registers a parser\n"
        "with `App::register_asset_type(name, directory, doc, parse)` and downcasts the parsed\n"
        "object itself.\n\n"
        "## Assets ship in packs\n\n"
        "`balaur export` bundles them, so a shipped game resolves an asset\n"
        "exactly as a dev run does. Binary assets (textures, audio, fonts)\n"
        "travel in the pack too, each carrying a content hash so a truncated\n"
        "entry is caught rather than handed on.\n"
    )
    return "".join(out)


def gen_flows(names):
    body = "# Behaviour covered by tests\n\nEvery test in the workspace, as a sentence. A flow that is not here is a\nflow nothing checks.\n\n"
    for n in names:
        body += f"- {n.replace('_', ' ')}\n"
    return body


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the files on disk are stale")
    args = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    crates = workspace()
    api = script_api()
    owners = module_owners()
    files = {
        "crates.md": gen_crates(crates),
        "crate-graph.md": gen_graph(crates),
        "script-api.md": gen_script_api(api, owners),
        "components.md": gen_components(
            api.get("components", {}),
            api.get("component_tags", {}),
            api.get("component_docs", {}),
            component_methods(api),
        ),
        "assets.md": gen_assets(
            api.get("asset_types", {}),
            # `modules` is a list of {name, functions, constants}.
            next(
                (m["functions"] for m in api.get("modules", []) if m["name"] == "assets"),
                [],
            ),
            api.get("components", {}),
        ),
        "behaviour.md": gen_flows(test_names()),
        # The raw probe, for tools that render their own reference (the
        # website builds its per-component pages from it).
        "api.json": json.dumps(api, indent=2, sort_keys=True) + "\n",
    }
    files["README.md"] = (
        "# Generated documentation\n\nRegenerated by `python3 scripts/gen_docs.py`; CI runs `--check` and fails on\ndrift. Do not edit these by hand.\n\n"
        + "".join(f"- [{n}]({n})\n" for n in sorted(files))
    )

    stale = []
    for name, body in files.items():
        # The banner is an HTML comment, which JSON has no room for.
        want = body if name.endswith(".json") else BANNER + body
        path = OUT / name
        if args.check:
            if not path.exists() or path.read_text() != want:
                stale.append(name)
        else:
            path.write_text(want)

    if args.check:
        if stale:
            print("stale generated docs: " + ", ".join(sorted(stale)), file=sys.stderr)
            print("run: python3 scripts/gen_docs.py", file=sys.stderr)
            return 1
        print(f"generated docs up to date ({len(files)} files)")
        return 0
    print(f"wrote {len(files)} files to docs/generated/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
