#!/usr/bin/env python3
"""Regenerate docs/generated/ from the workspace and a booted engine.

Hand-written docs go stale. These are derived, and CI runs --check, so they
are correct or the build is red.
"""
import argparse
import html
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "generated"
BANNER = "<!-- Generated by scripts/gen_docs.py. Do not edit; run `python3 scripts/gen_docs.py`. -->\n\n"


def run(*args):
    """Run a command, and on failure say what it printed.

    Without this the traceback shows only the exit code, which is useless when
    the interesting part is a compiler error thirty lines into stderr.
    """
    p = subprocess.run(args, cwd=ROOT, capture_output=True, text=True, check=False)
    if p.returncode != 0:
        print(f"command failed ({p.returncode}): {' '.join(args)}", file=sys.stderr)
        for stream, text in (("stdout", p.stdout), ("stderr", p.stderr)):
            if text.strip():
                print(f"--- {stream} ---\n{text.rstrip()}", file=sys.stderr)
        raise SystemExit(1)
    return p.stdout


def workspace():
    meta = json.loads(run("cargo", "metadata", "--no-deps", "--format-version", "1"))
    crates = {}
    for pkg in meta["packages"]:
        src = Path(pkg["manifest_path"]).parent
        crates[pkg["name"]] = {
            "description": pkg.get("description") or "",
            "deps": sorted(
                d["name"] for d in pkg["dependencies"]
                if d["name"].startswith("balaur") and d["kind"] is None
            ),
            "dev_deps": sorted(
                d["name"] for d in pkg["dependencies"]
                if d["name"].startswith("balaur") and d["kind"] == "dev"
            ),
            "external": sorted(
                d["name"] for d in pkg["dependencies"]
                if not d["name"].startswith("balaur") and d["kind"] is None
            ),
            "purpose": module_doc(src / "src" / "lib.rs") or module_doc(src / "src" / "main.rs"),
            "dir": src,
        }
    return dict(sorted(crates.items()))


def module_doc(path):
    """The leading //! block, as one paragraph."""
    if not path.exists():
        return ""
    lines = []
    for line in path.read_text().splitlines():
        if line.startswith("//!"):
            lines.append(line[3:].strip())
        elif lines:
            break
    while lines and not lines[-1]:
        lines.pop()
    para = []
    for line in lines:
        if not line:
            break
        para.append(line)
    return " ".join(para)


def public_surface(crate):
    """Count public items, and name the traits and types a crate owns."""
    kinds = {"fn": [], "struct": [], "enum": [], "trait": [], "const": [], "type": []}
    for rs in sorted((crate["dir"] / "src").rglob("*.rs")):
        for m in re.finditer(
            r"^pub (?:async )?(?:unsafe )?(fn|struct|enum|trait|const|type) ([A-Za-z_][A-Za-z0-9_]*)",
            rs.read_text(), re.M,
        ):
            kinds[m.group(1)].append(m.group(2))
    return {k: sorted(set(v)) for k, v in kinds.items()}


def script_api():
    out = run("cargo", "run", "-q", "-p", "balaur_cli", "--bin", "balaur", "--", "api")
    return json.loads(out)


def module_owners():
    """Which crate declares each script module, so backend-only ones show up."""
    owners = {}
    for rs in sorted((ROOT / "crates").rglob("src/**/*.rs")):
        crate = rs.relative_to(ROOT / "crates").parts[0]
        for m in re.finditer(r'(?:script_module|module)\(\s*(?:[^,()]+,\s*)*"([a-z0-9_]+)"\s*\)', rs.read_text()):
            owners.setdefault(m.group(1), crate)
    return owners


def test_names():
    """Every test, as a sentence. An undocumented flow is an untested one."""
    out = run("cargo", "test", "--workspace", "--", "--list")
    # Split off the trailing ": test", not the first colon: a name like
    # `det::tests::a_flow` would otherwise be reported as the module `det`.
    paths = [line.rsplit(":", 1)[0] for line in out.splitlines() if line.endswith(": test")]
    return sorted({p.rsplit("::", 1)[-1] for p in paths})


def write(name, body):
    (OUT / name).write_text(BANNER + body)


def gen_crates(crates):
    body = "# Crates\n\nOne section per workspace crate: what it is for, what it\ndepends on inside the workspace, and what it exports.\n\n"
    for name, c in crates.items():
        body += f"## `{name}`\n\n"
        if c["description"]:
            body += f"{c['description']}\n\n"
        if c["purpose"]:
            body += f"{c['purpose']}\n\n"
        body += f"- **workspace deps:** {', '.join(f'`{d}`' for d in c['deps']) or 'none'}\n"
        ext = c["external"]
        body += f"- **external deps:** {len(ext)}"
        if ext:
            body += f" ({', '.join(ext[:8])}{', …' if len(ext) > 8 else ''})"
        body += "\n"
        s = public_surface(c)
        counts = ", ".join(f"{len(v)} {k}" for k, v in s.items() if v) or "nothing public"
        body += f"- **public surface:** {counts}\n"
        for kind in ("trait", "struct", "enum"):
            if s[kind]:
                body += f"- **{kind}s:** {', '.join(f'`{n}`' for n in s[kind])}\n"
        body += "\n"
    return body


def gen_graph(crates):
    body = "# Crate graph\n\nWorkspace dependencies only. Backends depend on core; core never\ndepends on a backend, which is what keeps it language-free.\n\n```mermaid\ngraph TD\n"
    for name, c in crates.items():
        body += f"  {name}[{name}]\n"
    for name, c in crates.items():
        for d in c["deps"]:
            body += f"  {name} --> {d}\n"
    body += "```\n"
    return body


def gen_script_api(api, owners):
    body = "# Script API\n\nEvery module, function and constant a script can reach. Read from a booted\nengine rather than the source, so derived constants are included and this\ncannot drift from what scripts actually see.\n\n"
    backend_only = {m: o for m, o in owners.items() if o.startswith("balaur_script_")}
    body += "| Module | Functions | Constants | Available in |\n| --- | ---: | ---: | --- |\n"
    for m in api["modules"]:
        where = "Luau only" if m["name"] in backend_only else "every language"
        body += f"| [`{m['name']}`](#{m['name']}) | {len(m['functions'])} | {len(m['constants'])} | {where} |\n"
    body += "\n"
    for m in api["modules"]:
        body += f"## `{m['name']}`\n\n"
        if m["name"] in backend_only:
            body += f"Declared by `{backend_only[m['name']]}`, so it exists only on that backend.\n\n"
        if m["functions"]:
            body += "**Functions:** " + ", ".join(f"`{f}`" for f in m["functions"]) + "\n\n"
        if m["constants"]:
            body += f"**Constants** ({len(m['constants'])}):\n\n"
            shown = m["constants"][:24]
            body += "| Name | Value |\n| --- | --- |\n"
            for c in shown:
                body += f"| `{c['name']}` | `{c['value']}` |\n"
            if len(m["constants"]) > len(shown):
                body += f"\n…and {len(m['constants']) - len(shown)} more.\n"
            body += "\n"
    return body


def component_row(prop, spec):
    """One <tr>. HTML rather than a markdown table because the row lives
    inside <details>, where CommonMark leaves markdown unrendered."""
    notes = [html.escape(spec.get("description", ""))]
    if "options" in spec:
        notes.append("One of " + ", ".join(f"<code>{html.escape(o)}</code>" for o in spec["options"]) + ".")
    if "min" in spec or "max" in spec:
        low, high = spec.get("min", ""), spec.get("max", "")
        notes.append(f"Range {low}–{high}." if high != "" else f"At least {low}.")
    if spec.get("shorthand"):
        notes.append(f"Scene shorthand: <code>{html.escape(prop)}</code>'s value can be given as the component's whole value.")
    if spec.get("readonly"):
        notes.append("Read-only: engine output the inspector shows but never writes.")
    kind = spec.get("type", "")
    if kind == "asset":
        kind = f"asset · <code>{html.escape(spec.get('asset', ''))}</code>"
    else:
        kind = html.escape(kind)
    default = json.dumps(spec.get("default", "")).strip('"')
    cells = (
        f"<code>{html.escape(prop)}</code>",
        kind,
        f"<code>{html.escape(default)}</code>" if default else "—",
        " ".join(n for n in notes if n),
    )
    return "<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>"


def gen_components(components, asset_types):
    out = [
        "# Components\n\n",
        "Balaur has no node classes and no inheritance tree: every node is the\n"
        "same entity, and capability comes from the components on it.\n\n"
        "In the terms other engines use: a specialized node type there (a\n"
        "`RigidBody2D`, a `Sprite2D`, a `Label`) is here a plain node plus a\n"
        "component, and a content resource there (an animation library, say)\n"
        "is here an [asset](#asset-types), referenced from an `asset`-typed\n"
        "property or defined inline in the scene. Some things that are\n"
        "resources elsewhere are neither here: a collider's shape is plain\n"
        "data on the `collider` component itself. And similar component names\n"
        "are siblings by convention, never inheritance — `body2d` shares\n"
        "nothing with `body`; each component is independent and complete.\n\n"
        "Each component is registered by a plugin with the schema below; one\n"
        "registration provides the scene-file key, the runtime\n"
        "`node:set_component` family, and the editor's inspector rows.\n\n",
    ]
    for name in sorted(components):
        schema = components[name]
        props = sorted(schema)
        rows = "\n".join(component_row(p, schema[p]) for p in props)
        out.append(
            f"<details>\n<summary><code>{html.escape(name)}</code> · "
            f"{len(props)} propert{'y' if len(props) == 1 else 'ies'}</summary>\n"
            "<table>\n<thead><tr><th>property</th><th>type</th><th>default</th>"
            f"<th>description</th></tr></thead>\n<tbody>\n{rows}\n</tbody>\n</table>\n"
            "</details>\n\n"
        )
    out.append(
        "## Asset types\n\n"
        "Content that lives in files (or inline in a scene) rather than on a\n"
        "node, registered by plugins the same way components are. An\n"
        "`asset`-typed component property names which of these it takes.\n\n"
        "| type | project directory |\n| --- | --- |\n"
    )
    for name in sorted(asset_types):
        directory = asset_types[name]
        home = f"`{directory}/`" if directory else "— (not promotable to a file)"
        out.append(f"| `{name}` | {home} |\n")
    return "".join(out)


def gen_flows(names):
    body = "# Behaviour covered by tests\n\nEvery test in the workspace, as a sentence. A flow that is not here is a\nflow nothing checks.\n\n"
    for n in names:
        body += f"- {n.replace('_', ' ')}\n"
    return body


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the files on disk are stale")
    args = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    crates = workspace()
    api = script_api()
    owners = module_owners()
    files = {
        "crates.md": gen_crates(crates),
        "crate-graph.md": gen_graph(crates),
        "script-api.md": gen_script_api(api, owners),
        "components.md": gen_components(api.get("components", {}), api.get("asset_types", {})),
        "behaviour.md": gen_flows(test_names()),
    }
    files["README.md"] = (
        "# Generated documentation\n\nRegenerated by `python3 scripts/gen_docs.py`; CI runs `--check` and fails on\ndrift. Do not edit these by hand.\n\n"
        + "".join(f"- [{n}]({n})\n" for n in sorted(files))
    )

    stale = []
    for name, body in files.items():
        want = BANNER + body
        path = OUT / name
        if args.check:
            if not path.exists() or path.read_text() != want:
                stale.append(name)
        else:
            path.write_text(want)

    if args.check:
        if stale:
            print("stale generated docs: " + ", ".join(sorted(stale)), file=sys.stderr)
            print("run: python3 scripts/gen_docs.py", file=sys.stderr)
            return 1
        print(f"generated docs up to date ({len(files)} files)")
        return 0
    print(f"wrote {len(files)} files to docs/generated/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
