#!/usr/bin/env python3
"""Regenerate docs/generated/ from the workspace and a booted engine.

Hand-written docs go stale. These are derived, and CI runs --check, so they
are correct or the build is red.
"""
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "generated"
BANNER = "<!-- Generated by scripts/gen_docs.py. Do not edit; run `python3 scripts/gen_docs.py`. -->\n\n"


def run(*args):
    return subprocess.run(args, cwd=ROOT, capture_output=True, text=True, check=True).stdout


def workspace():
    meta = json.loads(run("cargo", "metadata", "--no-deps", "--format-version", "1"))
    crates = {}
    for pkg in meta["packages"]:
        src = Path(pkg["manifest_path"]).parent
        crates[pkg["name"]] = {
            "description": pkg.get("description") or "",
            "deps": sorted(
                d["name"] for d in pkg["dependencies"]
                if d["name"].startswith("balaur") and d["kind"] is None
            ),
            "dev_deps": sorted(
                d["name"] for d in pkg["dependencies"]
                if d["name"].startswith("balaur") and d["kind"] == "dev"
            ),
            "external": sorted(
                d["name"] for d in pkg["dependencies"]
                if not d["name"].startswith("balaur") and d["kind"] is None
            ),
            "purpose": module_doc(src / "src" / "lib.rs") or module_doc(src / "src" / "main.rs"),
            "dir": src,
        }
    return dict(sorted(crates.items()))


def module_doc(path):
    """The leading //! block, as one paragraph."""
    if not path.exists():
        return ""
    lines = []
    for line in path.read_text().splitlines():
        if line.startswith("//!"):
            lines.append(line[3:].strip())
        elif lines:
            break
    while lines and not lines[-1]:
        lines.pop()
    para = []
    for line in lines:
        if not line:
            break
        para.append(line)
    return " ".join(para)


def public_surface(crate):
    """Count public items, and name the traits and types a crate owns."""
    kinds = {"fn": [], "struct": [], "enum": [], "trait": [], "const": [], "type": []}
    for rs in sorted((crate["dir"] / "src").rglob("*.rs")):
        for m in re.finditer(
            r"^pub (?:async )?(?:unsafe )?(fn|struct|enum|trait|const|type) ([A-Za-z_][A-Za-z0-9_]*)",
            rs.read_text(), re.M,
        ):
            kinds[m.group(1)].append(m.group(2))
    return {k: sorted(set(v)) for k, v in kinds.items()}


def script_api():
    out = run("cargo", "run", "-q", "-p", "balaur_cli", "--bin", "balaur", "--", "api")
    return json.loads(out)


def module_owners():
    """Which crate declares each script module, so backend-only ones show up."""
    owners = {}
    for rs in sorted((ROOT / "crates").rglob("src/**/*.rs")):
        crate = rs.relative_to(ROOT / "crates").parts[0]
        for m in re.finditer(r'(?:script_module|module)\(\s*(?:[^,()]+,\s*)*"([a-z0-9_]+)"\s*\)', rs.read_text()):
            owners.setdefault(m.group(1), crate)
    return owners


def test_names():
    """Every test, as a sentence. An undocumented flow is an untested one."""
    out = run("cargo", "test", "--workspace", "--", "--list")
    names = sorted({line.split(":")[0] for line in out.splitlines() if line.endswith(": test")})
    return [n.rsplit("::", 1)[-1] for n in names]


def write(name, body):
    (OUT / name).write_text(BANNER + body)


def gen_crates(crates):
    body = "# Crates\n\nOne section per workspace crate: what it is for, what it\ndepends on inside the workspace, and what it exports.\n\n"
    for name, c in crates.items():
        body += f"## `{name}`\n\n"
        if c["description"]:
            body += f"{c['description']}\n\n"
        if c["purpose"]:
            body += f"{c['purpose']}\n\n"
        body += f"- **workspace deps:** {', '.join(f'`{d}`' for d in c['deps']) or 'none'}\n"
        ext = c["external"]
        body += f"- **external deps:** {len(ext)}"
        if ext:
            body += f" ({', '.join(ext[:8])}{', …' if len(ext) > 8 else ''})"
        body += "\n"
        s = public_surface(c)
        counts = ", ".join(f"{len(v)} {k}" for k, v in s.items() if v) or "nothing public"
        body += f"- **public surface:** {counts}\n"
        for kind in ("trait", "struct", "enum"):
            if s[kind]:
                body += f"- **{kind}s:** {', '.join(f'`{n}`' for n in s[kind])}\n"
        body += "\n"
    return body


def gen_graph(crates):
    body = "# Crate graph\n\nWorkspace dependencies only. Backends depend on core; core never\ndepends on a backend, which is what keeps it language-free.\n\n```mermaid\ngraph TD\n"
    for name, c in crates.items():
        body += f"  {name}[{name}]\n"
    for name, c in crates.items():
        for d in c["deps"]:
            body += f"  {name} --> {d}\n"
    body += "```\n"
    return body


def gen_script_api(api, owners):
    body = "# Script API\n\nEvery module, function and constant a script can reach. Read from a booted\nengine rather than the source, so derived constants are included and this\ncannot drift from what scripts actually see.\n\n"
    backend_only = {m: o for m, o in owners.items() if o.startswith("balaur_script_")}
    body += "| Module | Functions | Constants | Available in |\n| --- | ---: | ---: | --- |\n"
    for m in api["modules"]:
        where = "Luau only" if m["name"] in backend_only else "every language"
        body += f"| [`{m['name']}`](#{m['name']}) | {len(m['functions'])} | {len(m['constants'])} | {where} |\n"
    body += "\n"
    for m in api["modules"]:
        body += f"## `{m['name']}`\n\n"
        if m["name"] in backend_only:
            body += f"Declared by `{backend_only[m['name']]}`, so it exists only on that backend.\n\n"
        if m["functions"]:
            body += "**Functions:** " + ", ".join(f"`{f}`" for f in m["functions"]) + "\n\n"
        if m["constants"]:
            body += f"**Constants** ({len(m['constants'])}):\n\n"
            shown = m["constants"][:24]
            body += "| Name | Value |\n| --- | --- |\n"
            for c in shown:
                body += f"| `{c['name']}` | `{c['value']}` |\n"
            if len(m["constants"]) > len(shown):
                body += f"\n…and {len(m['constants']) - len(shown)} more.\n"
            body += "\n"
    return body


def gen_flows(names):
    body = "# Behaviour covered by tests\n\nEvery test in the workspace, as a sentence. A flow that is not here is a\nflow nothing checks.\n\n"
    for n in names:
        body += f"- {n.replace('_', ' ')}\n"
    return body


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the files on disk are stale")
    args = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    crates = workspace()
    api = script_api()
    owners = module_owners()
    files = {
        "crates.md": gen_crates(crates),
        "crate-graph.md": gen_graph(crates),
        "script-api.md": gen_script_api(api, owners),
        "behaviour.md": gen_flows(test_names()),
    }
    files["README.md"] = (
        "# Generated documentation\n\nRegenerated by `python3 scripts/gen_docs.py`; CI runs `--check` and fails on\ndrift. Do not edit these by hand.\n\n"
        + "".join(f"- [{n}]({n})\n" for n in sorted(files))
    )

    stale = []
    for name, body in files.items():
        want = BANNER + body
        path = OUT / name
        if args.check:
            if not path.exists() or path.read_text() != want:
                stale.append(name)
        else:
            path.write_text(want)

    if args.check:
        if stale:
            print("stale generated docs: " + ", ".join(sorted(stale)), file=sys.stderr)
            print("run: python3 scripts/gen_docs.py", file=sys.stderr)
            return 1
        print(f"generated docs up to date ({len(files)} files)")
        return 0
    print(f"wrote {len(files)} files to docs/generated/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
