#!/usr/bin/env python3
"""Prose lints for the hand-written documents in this tree.

Two rule sets, on two scopes.

**House rules**, on the two documents that flow into the website: a sentence
is under 35 words, no filler, and an em dash is typography only at the lead of
a list item or a roadmap row, never a splice in prose. The rule is the
website's (balaur-website scripts/lint-prose.mjs).

**Roadmap rows**, on `docs/ROADMAP.md`: the website draws each row as a card,
so a row is one sentence and at most 25 words. Its generator warns rather than
failing, so this is the gate.

**Machine-writing rules**, on every hand-written `.md` here. The mechanical
half of the `avoid-ai-writing` skill, which cannot run in CI because it is a
model: the vocabulary a language model reaches for, the transitions it opens
with, the closers it lands on, and the markup its chat interfaces leak. A
model still has to judge tone; this catches what a regex can.

Two severities, as in house_lints.py:
  ERROR  fails CI. Unambiguous: a word with a plain replacement, a chatbot
         artifact, a leaked citation token.
  REPORT printed, never failing. Judgement calls that need a reader.

  python3 scripts/prose_lints.py                 # exit 0 unless ERROR
  python3 scripts/prose_lints.py --fail-on-error # same, explicit
  python3 scripts/prose_lints.py --reports       # show REPORT findings too
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ERRORS: list[str] = []
REPORTS = ["docs/ROADMAP.md"]

MAX_SENTENCE = 35

# The website draws every roadmap row as a card, so a row is one sentence and
# at most 25 words. Its generator (balaur-website scripts/gen-roadmap.mjs)
# warns and builds the page anyway rather than losing a deploy to a sentence
# written here, so this is the gate: the limit is checked where the file is.
ROADMAP = "docs/ROADMAP.md"
ROW_SENTENCES = 1
ROW_WORDS = 25

# Throat-clearing; the fix is to delete it.
PHRASES = [
    r"\bhonest(ly)?\b", r"\bactually\b", r"\btruly\b", r"\bgenuinely\b",
    r"\bit(?:'s| is) worth\b", r"\bworth (?:noting|a look|mentioning)\b",
    r"\bthe question (?:was|is)\b", r"\blet's\b", r"\bto be (?:clear|fair)\b",
    r"\bsimply put\b", r"\bin order to\b", r"\bat its core\b",
    r"\bleverag(?:e|es|ed|ing)\b", r"\bdelv(?:e|es|ed|ing)\b", r"\bseamless(?:ly)?\b",
]

# The em dash that is typography: `- **Term** — text`, `| **Term** — text`.
LEAD_DASH = re.compile(r"^\s*(?:[-*]|\d+\.|\|)\s*(?:\*\*[^*]+\*\*|`[^`]+`|\[[^\]]+\]\([^)]+\))\s*—\s")


# Every hand-written `.md` here. `docs/generated/` is written by gen_docs.py
# from the engine, and a lint on it would be a lint on the engine's own doc
# strings, which api_lints.py already covers.
def documents() -> list[Path]:
    out = [p for p in ROOT.glob("*.md")]
    out += [p for p in ROOT.glob("docs/**/*.md") if "generated" not in p.parts]
    out += [p for p in ROOT.glob("editors/**/*.md") if "node_modules" not in p.parts]
    return sorted(p for p in out if not generated(p))


def generated(path: Path) -> bool:
    """Whether a file says it was written by a script. Its prose is the
    generator's, or a third party's, and neither is edited here."""
    head = path.read_text(encoding="utf-8")[:200]
    return "Generated by" in head or "Do not edit" in head


# Words a language model reaches for where a plain one exists. The left side
# is what to match, the right what to write instead.
VOCABULARY = {
    r"delv(?:e|es|ed|ing)": "explore, dig into",
    r"leverag(?:e|es|ed|ing)": "use",
    r"utiliz(?:e|es|ed|ing)": "use",
    r"robust": "strong, reliable",
    r"comprehensive": "thorough, complete",
    r"cutting-edge": "latest, newest",
    r"pivotal": "important, key",
    r"meticulous(?:ly)?": "careful, precise",
    r"seamless(?:ly)?": "smooth, without friction",
    r"game-chang(?:er|ing)": "say what changed",
    r"showcas(?:ed|ing)": "show, demonstrate",
    r"deep dive": "look at, examine",
    r"unpacking (?:the|this|it)": "explain, break down",
    r"intricate|intricacies": "complex, or name the complexity",
    r"ever-evolving": "changing, growing",
    r"daunting": "hard, difficult",
    r"holistic(?:ally)?": "complete, whole",
    r"actionable": "practical, concrete",
    r"impactful": "effective, or describe the impact",
    r"learnings": "lessons, findings",
    r"best practices": "what works, the standard approach",
    r"at its core": "cut it; state the thing",
    r"synerg(?:y|ies)": "describe the combined effect",
    r"testament to": "shows, proves",
    r"tapestry": "describe the actual complexity",
    r"nestled": "sits, is in",
    r"vibrant|bustling": "describe what makes it active",
    r"thriving": "growing, or cite a number",
    r"in order to": "to",
    r"due to the fact that": "because",
    r"boasts": "has",
    r"commence(?:s|d)?": "start, begin",
    r"ascertain": "find out, determine",
    r"paradigm": "model, approach",
    r"embark(?:s|ed|ing)?": "start, begin",
}

# Shapes, not words. Each is a construction a model produces and a person
# writing plainly does not.
SHAPES = {
    "chatbot": (r"I hope this helps|great question|feel free to reach out|"
                r"let me know if you need|in this article,? we(?:'ll| will)|let's dive in",
                "a chat interface's voice, not writing"),
    "transition": (r"^\s*(?:moreover|furthermore|additionally)\b",
                   "restructure so the connection is plain, or use \"and\""),
    "throat-clearing": (r"\bin today's\b|\bin an era where\b|\bin conclusion\b|"
                        r"\bat the end of the day\b|\bwhen it comes to\b|\bthat being said\b",
                        "cut it and state the point"),
    "hedge-stack": (r"could potentially|may eventually|might ultimately|may potentially",
                    "one hedge or none"),
    "generic-closer": (r"the future looks bright|only time will tell|"
                       r"one thing is certain|as we move forward",
                       "say something specific or nothing"),
    "vague-attribution": (r"experts (?:believe|agree|say)|studies show|"
                          r"research suggests|industry leaders agree",
                          "name the source or drop the attribution"),
    "cutoff": (r"as of my last update|I do(?:n't| not) have access to real-time|"
               r"based on available information",
               "a model's limits leaking into prose; look it up or cut it"),
    "leak": (r"citeturn|oaicite|contentReference|utm_source=(?:chatgpt|claude|openai|perplexity|copilot)",
             "chat markup pasted through; delete it"),
    "placeholder": (r"\[(?:your|insert|add|enter|describe|specify) [^\]]+\]|\b\d{4}-XX-XX\b",
                    "an unfilled slot; fill it in or cut the sentence"),
    "speculative-opener": (r"imagine a world where|picture a future|envision a world",
                           "state the claim instead of the scenario"),
    "inflation": (r"watershed moment|marking a pivotal moment|"
                  r"a (?:significant|major) step (?:towards|forward)",
                  "state what happened and let the reader judge"),
    "false-breadth": (r"whether you(?:'re| are) (?:a|an) [^,]+ or (?:a|an)",
                      "name the audience you mean, or cut"),
}

# Judgement calls: real tells, but each has an honest use this cannot tell
# apart, so they print and never fail. A bolded label closed with a period is
# not here: it reads the same as the claim form AGENTS.md asks for.
SOFT = {
    "intensifier": (r"\b(?:real|actual|genuine|true) (?:utility|value|accuracy|"
                    r"sustainability|adoption|impact)\b",
                    "name what the unreal version is, or drop the adjective"),
    "hook": (r"^\s*(?:the catch\?|the kicker\?|here's the thing|plot twist:|"
             r"the best part\?|the result\?)",
             "state the thing without the tease"),
}


@dataclass
class Finding:
    path: str
    line: int
    rule: str
    message: str


def prose(line: str) -> str:
    """One line of markdown as plain words; inline code is one word."""
    t = re.sub(r"^\s*(?:[-*]|\d+\.)\s+", "", line)
    t = re.sub(r"!\[[^\]]*\]\([^)]*\)", "", t)
    t = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", t)
    t = re.sub(r"`[^`]*`", "X", t)
    t = re.sub(r"<[^>]+>", "", t)
    t = t.replace("**", "").replace("__", "").replace("*", "")
    return t.strip()


def sentences(text: str) -> list[str]:
    text = re.sub(r"\b(e\.g|i\.e|vs|etc|cf)\.", r"\1", text, flags=re.I)
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+(?=[A-Za-z0-9\"'X\[(`])", text) if s.strip()]


def machine_writing(path: Path) -> tuple[list[Finding], list[Finding]]:
    """The mechanical half of `avoid-ai-writing`, as (errors, reports).

    Reads the same prose the house rules do: fences, headings and inline code
    are not prose, and a table cell is.
    """
    errors: list[Finding] = []
    reports: list[Finding] = []
    rel = str(path.relative_to(ROOT))
    fence = False
    for n, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if raw.lstrip().startswith("```"):
            fence = not fence
            continue
        if fence or not raw.strip():
            continue
        # A leak or a placeholder is a defect wherever it lands, headings
        # and code included; everything else is judged on the prose.
        for rule in ("leak", "placeholder"):
            pattern, fix = SHAPES[rule]
            if m := re.search(pattern, raw, re.I):
                errors.append(Finding(rel, n, rule, f"\"{m.group(0)[:40]}\": {fix}"))
        if raw.lstrip().startswith(("#", "<!--", ">")):
            continue
        cells = raw.split("|") if raw.lstrip().startswith("|") else [raw]
        text = " ".join(prose(c) for c in cells).strip()
        if re.fullmatch(r"[-:\s]*", text):
            continue
        for word, fix in VOCABULARY.items():
            if m := re.search(rf"\b(?:{word})\b", text, re.I):
                errors.append(Finding(rel, n, "vocabulary", f"\"{m.group(0)}\": {fix}"))
        for rule, (pattern, fix) in SHAPES.items():
            if rule in ("leak", "placeholder"):
                continue
            if m := re.search(pattern, text, re.I):
                errors.append(Finding(rel, n, rule, f"\"{m.group(0)[:40]}\": {fix}"))
        for rule, (pattern, fix) in SOFT.items():
            if m := re.search(pattern, raw, re.I):
                reports.append(Finding(rel, n, rule, f"\"{m.group(0)[:40]}\": {fix}"))
    return errors, reports


def lint(path: Path) -> list[Finding]:
    out: list[Finding] = []
    rel = str(path.relative_to(ROOT))
    fence = False
    for n, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if raw.lstrip().startswith("```"):
            fence = not fence
            continue
        if fence or not raw.strip() or raw.lstrip().startswith(("#", "<!--")):
            continue
        # A table row: the first cell is the prose; the rest are tier and plan.
        cells = [c for c in raw.split("|")] if raw.lstrip().startswith("|") else [raw]
        text = prose(cells[1] if len(cells) > 2 else cells[0])
        if re.fullmatch(r"[-:\s]*", text):
            continue
        for s in sentences(text):
            words = len(s.split())
            if words > MAX_SENTENCE:
                out.append(Finding(rel, n, "sentence-length",
                                   f"{words}-word sentence; the limit is {MAX_SENTENCE}: \"{s[:60]}…\""))
        for p in PHRASES:
            m = re.search(p, text, re.I)
            if m:
                out.append(Finding(rel, n, "phrase", f"\"{m.group(0)}\": say the fact without it"))
        if "—" in raw and not LEAD_DASH.match(raw):
            out.append(Finding(rel, n, "em-dash", "em dash in prose; use a comma, a colon, a period or a list"))
    return out


def roadmap_rows(path: Path) -> list[Finding]:
    """Each `| **Title** — text | milestone | plan |` row, measured as the card
    the website builds from it. Rows under `## Milestones` are that table, not
    items, and a row whose milestone is parenthesised is in-tree work the page
    never shows; both are skipped, as the generator skips them."""
    out: list[Finding] = []
    rel = str(path.relative_to(ROOT))
    group = None
    for n, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if raw.startswith("## "):
            heading = raw[3:].strip()
            group = None if heading == "Milestones" else heading
            continue
        if not group or not raw.startswith("| ") or re.match(r"^\|\s*(?:Item|Milestone|:?-{3,})", raw):
            continue
        cells = [c.strip() for c in raw.strip().strip("|").split(" | ")]
        if len(cells) != 3 or re.fullmatch(r"\(.+\)", cells[1]):
            continue
        row = re.match(r"^\*\*(.+?)\*\*\s+—\s(.+)$", cells[0])
        if not row:
            continue
        title, text = row.group(1).replace("`", ""), row.group(2).replace("`", "").strip()
        n_sentences, n_words = len(sentences(text)), len(text.split())
        if n_sentences > ROW_SENTENCES or n_words > ROW_WORDS:
            out.append(Finding(rel, n, "roadmap-row",
                               f"\"{title}\" is {n_sentences} sentence(s) and {n_words} words; "
                               f"a card is {ROW_SENTENCES} sentence and at most {ROW_WORDS} words"))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--fail-on-error", action="store_true")
    ap.add_argument("--reports", action="store_true", help="also print REPORT findings")
    args = ap.parse_args()
    errors = [f for name in ERRORS if (ROOT / name).exists() for f in lint(ROOT / name)]
    if (ROOT / ROADMAP).exists():
        errors += roadmap_rows(ROOT / ROADMAP)
    reports = [f for name in REPORTS if (ROOT / name).exists() for f in lint(ROOT / name)]
    docs = documents()
    for doc in docs:
        found, soft = machine_writing(doc)
        errors += found
        reports += soft
    for f in errors:
        print(f"ERROR  {f.path}:{f.line}  [{f.rule}] {f.message}")
    if args.reports:
        for f in reports:
            print(f"report {f.path}:{f.line}  [{f.rule}] {f.message}")
    print(f"\n{len(docs)} files · {len(errors)} errors · {len(reports)} reports")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
