#!/usr/bin/env python3
"""Regenerate THIRD-PARTY-NOTICES.md from the dependency graph.

Balaur's own source is MIT, but a built binary is a combined work: the graph
carries Apache-2.0-only, MPL-2.0 and BSD-3-Clause crates, and every one of
those licences obliges us to pass its text and its copyright line on to
whoever receives the binary. This walks the graph and writes that file.

Dev-dependencies are excluded: criterion and tempfile are not in anything we
ship. Everything reachable from a workspace crate as a normal or build
dependency is included, for every platform, because the exporter ships to all
of them from one source tree.

Usage:
  python3 scripts/third_party_notices.py            # rewrite the file
  python3 scripts/third_party_notices.py --check    # fail if it would change
"""
import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "THIRD-PARTY-NOTICES.md"
BANNER = (
    "<!-- Generated by scripts/third_party_notices.py. Do not edit; run "
    "`python3 scripts/third_party_notices.py`. -->\n\n"
)

LICENCE_FILE = re.compile(
    r"^(licen[cs]e|copying|notice|unlicen[cs]e|copyright)([-_.].*)?$", re.IGNORECASE
)
# Files that match the name but carry no licence text.
SKIP_SUFFIX = (".rs", ".py", ".toml", ".json", ".lock")


def metadata():
    """The full graph, all features, so the windowed and mobile trees count."""
    out = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--all-features"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if out.returncode != 0:
        print(out.stderr, file=sys.stderr)
        sys.exit(f"cargo metadata failed ({out.returncode})")
    return json.loads(out.stdout)


def shipped(meta):
    """Package ids reachable from a workspace crate, dev-dependencies aside."""
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    members = set(meta["workspace_members"])
    seen, queue = set(members), list(members)
    while queue:
        node = nodes.get(queue.pop())
        if not node:
            continue
        for dep in node["deps"]:
            kinds = {k.get("kind") for k in dep.get("dep_kinds", [{"kind": None}])}
            if kinds <= {"dev"} or dep["pkg"] in seen:
                continue
            seen.add(dep["pkg"])
            queue.append(dep["pkg"])
    return seen - members


def licence_texts(pkg):
    """Every licence-ish file sitting beside the crate's manifest."""
    found = []
    for path in sorted(Path(pkg["manifest_path"]).parent.iterdir()):
        if not path.is_file() or path.suffix.lower() in SKIP_SUFFIX:
            continue
        if not LICENCE_FILE.match(path.name):
            continue
        try:
            text = path.read_text(encoding="utf-8").strip()
        except (UnicodeDecodeError, OSError):
            continue
        if text:
            found.append((path.name, text))
    return found


def expression(pkg):
    if pkg.get("license"):
        # Old-style slashes mean OR; SPDX has not accepted them since 2018.
        return " ".join(pkg["license"].replace("/", " OR ").split())
    if pkg.get("license_file"):
        return f"see {Path(pkg['license_file']).name}"
    return "UNDECLARED"


def render(meta):
    ids = shipped(meta)
    pkgs = sorted(
        (p for p in meta["packages"] if p["id"] in ids),
        key=lambda p: (p["name"].lower(), p["version"]),
    )

    # One copy of each distinct licence text, with the crates that carry it.
    texts, users = {}, {}
    for pkg in pkgs:
        for name, text in licence_texts(pkg):
            key = hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]
            texts.setdefault(key, (name, text))
            users.setdefault(key, []).append(f"{pkg['name']} {pkg['version']}")

    by_expr = {}
    for pkg in pkgs:
        by_expr.setdefault(expression(pkg), []).append(pkg)

    out = [BANNER, "# Third-party notices\n\n"]
    out.append(
        "Balaur's own source is licensed MIT (see [LICENSE](LICENSE)). A built\n"
        "engine, editor or exported game is a combined work that also contains the\n"
        f"{len(pkgs)} packages listed here, some under licences that are not MIT.\n"
        "Ship this file with any binary you distribute.\n\n"
        "Two consequences worth stating plainly:\n\n"
        "- Apache-2.0-only components (rapier, parry, winit, nalgebra and others)\n"
        "  make the combined work incompatible with **GPL-2.0-only**. GPL-3.0,\n"
        "  LGPL, AGPL and proprietary licensing of a game are unaffected.\n"
        "- MPL-2.0 components (the symphonia family) are file-level copyleft:\n"
        "  linking is unrestricted, but a patch to one of *their* files has to be\n"
        "  published. We vendor none of them today.\n\n"
        "Regenerate with `python3 scripts/third_party_notices.py`.\n\n"
    )

    out.append("## Licences in the graph\n\n")
    out.append("| Licence | Packages |\n| --- | --- |\n")
    for expr, group in sorted(by_expr.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        out.append(f"| `{expr}` | {len(group)} |\n")

    out.append("\n## Packages\n\n")
    out.append("| Package | Version | Licence |\n| --- | --- | --- |\n")
    for pkg in pkgs:
        link = pkg.get("repository") or ""
        name = f"[{pkg['name']}]({link})" if link else pkg["name"]
        out.append(f"| {name} | {pkg['version']} | `{expression(pkg)}` |\n")

    out.append("\n## Licence texts\n\n")
    missing = sorted({p["name"] for p in pkgs if not licence_texts(p)})
    if missing:
        out.append(
            "These packages ship no licence file in their published archive, so the\n"
            "SPDX expression in the table above is the whole of what their authors\n"
            "granted; where it names a licence, that licence's text appears below,\n"
            f"reproduced from a crate that does ship it: {', '.join(missing)}.\n\n"
        )
    order = sorted(texts, key=lambda k: (-len(set(users[k])), users[k][0].lower()))
    for key in order:
        name, text = texts[key]
        crates = sorted(set(users[key]))
        out.append(f"### {name} — {len(crates)} package{'s' if len(crates) > 1 else ''}\n\n")
        out.append("<details>\n<summary>Which packages carry this exact file</summary>\n\n")
        out.append(", ".join(crates) + "\n\n</details>\n\n")
        out.append("```\n" + text.replace("\r\n", "\n") + "\n```\n\n")
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = ap.parse_args()

    text = render(metadata())
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.name} is stale; run python3 scripts/third_party_notices.py")
            return 1
        print(f"{OUT.name} is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text) // 1024} KiB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
