//! Every key a backend reports. A key's value is its W3C `KeyboardEvent.code`,
//! which the web sends as it is and winit's `KeyCode` spells the same way, so
//! a binding written on one platform reads the same key on another.

/// Every physical key: the `input.KEY_*` constant, and the code it holds.
pub const KEYS: &[(&str, &str)] = &[
    ("KEY_A", "KeyA"),
    ("KEY_B", "KeyB"),
    ("KEY_C", "KeyC"),
    ("KEY_D", "KeyD"),
    ("KEY_E", "KeyE"),
    ("KEY_F", "KeyF"),
    ("KEY_G", "KeyG"),
    ("KEY_H", "KeyH"),
    ("KEY_I", "KeyI"),
    ("KEY_J", "KeyJ"),
    ("KEY_K", "KeyK"),
    ("KEY_L", "KeyL"),
    ("KEY_M", "KeyM"),
    ("KEY_N", "KeyN"),
    ("KEY_O", "KeyO"),
    ("KEY_P", "KeyP"),
    ("KEY_Q", "KeyQ"),
    ("KEY_R", "KeyR"),
    ("KEY_S", "KeyS"),
    ("KEY_T", "KeyT"),
    ("KEY_U", "KeyU"),
    ("KEY_V", "KeyV"),
    ("KEY_W", "KeyW"),
    ("KEY_X", "KeyX"),
    ("KEY_Y", "KeyY"),
    ("KEY_Z", "KeyZ"),
    ("KEY_0", "Digit0"),
    ("KEY_1", "Digit1"),
    ("KEY_2", "Digit2"),
    ("KEY_3", "Digit3"),
    ("KEY_4", "Digit4"),
    ("KEY_5", "Digit5"),
    ("KEY_6", "Digit6"),
    ("KEY_7", "Digit7"),
    ("KEY_8", "Digit8"),
    ("KEY_9", "Digit9"),
    ("KEY_F1", "F1"),
    ("KEY_F2", "F2"),
    ("KEY_F3", "F3"),
    ("KEY_F4", "F4"),
    ("KEY_F5", "F5"),
    ("KEY_F6", "F6"),
    ("KEY_F7", "F7"),
    ("KEY_F8", "F8"),
    ("KEY_F9", "F9"),
    ("KEY_F10", "F10"),
    ("KEY_F11", "F11"),
    ("KEY_F12", "F12"),
    ("KEY_F13", "F13"),
    ("KEY_F14", "F14"),
    ("KEY_F15", "F15"),
    ("KEY_F16", "F16"),
    ("KEY_F17", "F17"),
    ("KEY_F18", "F18"),
    ("KEY_F19", "F19"),
    ("KEY_F20", "F20"),
    ("KEY_F21", "F21"),
    ("KEY_F22", "F22"),
    ("KEY_F23", "F23"),
    ("KEY_F24", "F24"),
    ("KEY_ESCAPE", "Escape"),
    ("KEY_TAB", "Tab"),
    ("KEY_SPACE", "Space"),
    ("KEY_BACKSPACE", "Backspace"),
    ("KEY_ENTER", "Enter"),
    ("KEY_CAPS_LOCK", "CapsLock"),
    ("KEY_NUM_LOCK", "NumLock"),
    ("KEY_SCROLL_LOCK", "ScrollLock"),
    ("KEY_PRINT_SCREEN", "PrintScreen"),
    ("KEY_PAUSE", "Pause"),
    ("KEY_INSERT", "Insert"),
    ("KEY_DELETE", "Delete"),
    ("KEY_HOME", "Home"),
    ("KEY_END", "End"),
    ("KEY_PAGE_UP", "PageUp"),
    ("KEY_PAGE_DOWN", "PageDown"),
    ("KEY_LEFT", "ArrowLeft"),
    ("KEY_RIGHT", "ArrowRight"),
    ("KEY_UP", "ArrowUp"),
    ("KEY_DOWN", "ArrowDown"),
    ("KEY_LEFT_SHIFT", "ShiftLeft"),
    ("KEY_RIGHT_SHIFT", "ShiftRight"),
    ("KEY_LEFT_CONTROL", "ControlLeft"),
    ("KEY_RIGHT_CONTROL", "ControlRight"),
    ("KEY_LEFT_ALT", "AltLeft"),
    ("KEY_RIGHT_ALT", "AltRight"),
    ("KEY_LEFT_META", "MetaLeft"),
    ("KEY_RIGHT_META", "MetaRight"),
    ("KEY_BACKQUOTE", "Backquote"),
    ("KEY_APOSTROPHE", "Quote"),
    ("KEY_MINUS", "Minus"),
    ("KEY_EQUAL", "Equal"),
    ("KEY_COMMA", "Comma"),
    ("KEY_PERIOD", "Period"),
    ("KEY_SLASH", "Slash"),
    ("KEY_BACKSLASH", "Backslash"),
    ("KEY_SEMICOLON", "Semicolon"),
    ("KEY_LEFT_BRACKET", "BracketLeft"),
    ("KEY_RIGHT_BRACKET", "BracketRight"),
    ("KEY_INTERNATIONAL_BACKSLASH", "IntlBackslash"),
    ("KEY_INTERNATIONAL_YEN", "IntlYen"),
    ("KEY_INTERNATIONAL_RO", "IntlRo"),
    ("KEY_CONTEXT_MENU", "ContextMenu"),
    ("KEY_NUMPAD_0", "Numpad0"),
    ("KEY_NUMPAD_1", "Numpad1"),
    ("KEY_NUMPAD_2", "Numpad2"),
    ("KEY_NUMPAD_3", "Numpad3"),
    ("KEY_NUMPAD_4", "Numpad4"),
    ("KEY_NUMPAD_5", "Numpad5"),
    ("KEY_NUMPAD_6", "Numpad6"),
    ("KEY_NUMPAD_7", "Numpad7"),
    ("KEY_NUMPAD_8", "Numpad8"),
    ("KEY_NUMPAD_9", "Numpad9"),
    ("KEY_NUMPAD_ADD", "NumpadAdd"),
    ("KEY_NUMPAD_SUBTRACT", "NumpadSubtract"),
    ("KEY_NUMPAD_MULTIPLY", "NumpadMultiply"),
    ("KEY_NUMPAD_DIVIDE", "NumpadDivide"),
    ("KEY_NUMPAD_PERIOD", "NumpadDecimal"),
    ("KEY_NUMPAD_ENTER", "NumpadEnter"),
    ("KEY_NUMPAD_EQUAL", "NumpadEqual"),
    ("KEY_NUMPAD_COMMA", "NumpadComma"),
    ("KEY_MEDIA_PLAY_PAUSE", "MediaPlayPause"),
    ("KEY_MEDIA_STOP", "MediaStop"),
    ("KEY_MEDIA_TRACK_NEXT", "MediaTrackNext"),
    ("KEY_MEDIA_TRACK_PREVIOUS", "MediaTrackPrevious"),
    ("KEY_MEDIA_SELECT", "MediaSelect"),
    ("KEY_AUDIO_VOLUME_MUTE", "AudioVolumeMute"),
    ("KEY_AUDIO_VOLUME_DOWN", "AudioVolumeDown"),
    ("KEY_AUDIO_VOLUME_UP", "AudioVolumeUp"),
    ("KEY_BROWSER_BACK", "BrowserBack"),
    ("KEY_BROWSER_FORWARD", "BrowserForward"),
    ("KEY_BROWSER_HOME", "BrowserHome"),
    ("KEY_BROWSER_REFRESH", "BrowserRefresh"),
    ("KEY_BROWSER_SEARCH", "BrowserSearch"),
    ("KEY_LAUNCH_MAIL", "LaunchMail"),
    ("KEY_POWER", "Power"),
    ("KEY_SLEEP", "Sleep"),
    ("KEY_WAKE_UP", "WakeUp"),
    ("KEY_KANA_MODE", "KanaMode"),
    ("KEY_CONVERT", "Convert"),
    ("KEY_NON_CONVERT", "NonConvert"),
    ("KEY_COPY", "Copy"),
    ("KEY_PASTE", "Paste"),
    ("KEY_CUT", "Cut"),
];

/// A modifier on either side: the constant, the value a script passes, and
/// the two codes it answers to.
pub const EITHER_SIDE: &[(&str, &str, [&str; 2])] = &[
    ("KEY_SHIFT", "Shift", ["ShiftLeft", "ShiftRight"]),
    ("KEY_CONTROL", "Control", ["ControlLeft", "ControlRight"]),
    ("KEY_ALT", "Alt", ["AltLeft", "AltRight"]),
    ("KEY_META", "Meta", ["MetaLeft", "MetaRight"]),
];

/// Whether `test` holds for the key a script named: its own code, or either
/// side of a modifier.
pub(crate) fn any_code(key: &str, test: impl Fn(&str) -> bool) -> bool {
    match EITHER_SIDE.iter().find(|(_, name, _)| *name == key) {
        Some((_, _, sides)) => sides.iter().any(|side| test(side)),
        None => test(key),
    }
}
