//! What a Godot shader name becomes in WGSL: its types, a name that collides
//! with a WGSL word, a swizzle, and the built-ins with no counterpart.

use anyhow::{Result, bail};

use crate::import_godot_shader_syntax::TYPES;

/// WGSL's keywords and reserved words a Godot name may collide with, and
/// the names this translation declares itself.
const RESERVED: &[&str] = &[
    "alias",
    "break",
    "case",
    "const",
    "const_assert",
    "continue",
    "continuing",
    "default",
    "diagnostic",
    "discard",
    "else",
    "enable",
    "false",
    "fn",
    "for",
    "if",
    "let",
    "loop",
    "override",
    "requires",
    "return",
    "struct",
    "switch",
    "true",
    "var",
    "while",
    "NULL",
    "Self",
    "abstract",
    "active",
    "alignas",
    "alignof",
    "as",
    "asm",
    "async",
    "attribute",
    "auto",
    "await",
    "become",
    "cast",
    "catch",
    "class",
    "coherent",
    "column_major",
    "common",
    "compile",
    "concept",
    "constexpr",
    "crate",
    "debugger",
    "decltype",
    "delete",
    "demote",
    "do",
    "enum",
    "explicit",
    "export",
    "extends",
    "extern",
    "external",
    "fallthrough",
    "filter",
    "final",
    "finally",
    "friend",
    "from",
    "get",
    "goto",
    "handle",
    "impl",
    "implements",
    "import",
    "inline",
    "instanceof",
    "interface",
    "layout",
    "macro",
    "match",
    "meta",
    "mod",
    "module",
    "move",
    "mut",
    "mutable",
    "namespace",
    "new",
    "nil",
    "noexcept",
    "noinline",
    "null",
    "nullptr",
    "of",
    "operator",
    "package",
    "packoffset",
    "partition",
    "pass",
    "patch",
    "precise",
    "precision",
    "priv",
    "protected",
    "pub",
    "public",
    "readonly",
    "ref",
    "register",
    "resource",
    "restrict",
    "self",
    "set",
    "shared",
    "sizeof",
    "smooth",
    "snorm",
    "static",
    "std",
    "subroutine",
    "super",
    "target",
    "template",
    "this",
    "throw",
    "trait",
    "try",
    "type",
    "typedef",
    "typeid",
    "typename",
    "typeof",
    "union",
    "unless",
    "unorm",
    "unsafe",
    "unsized",
    "use",
    "using",
    "virtual",
    "volatile",
    "wgsl",
    "where",
    "with",
    "writeonly",
    "yield",
    "f32",
    "f16",
    "i32",
    "u32",
    "bool",
    "vec2",
    "vec3",
    "vec4",
    "mat2x2",
    "mat3x3",
    "mat4x4",
    "array",
    "ptr",
    "sampler",
    "texture_2d",
    "in",
    "out",
    "params",
    "Params",
    "Varyings",
    "vs_main",
    "fs_main",
    "godot_in",
    "godot_base",
    "godot_finish",
    "VertexInput",
    "VertexOutput",
    "vertex",
    "place",
    "tint",
    "time",
    "sample_albedo",
    "screen_uv",
    "sample_screen",
    "texture_pixel_size",
    "screen_pixel_size",
    "vertex_pixels",
    "pixels_to_offset",
    "model_matrix_pixels",
    "albedo_texture",
    "albedo_sampler",
    "screen_texture",
    "screen_sampler",
    "frame",
    "object",
    "texture_1",
    "texture_2",
    "texture_3",
    "texture_4",
    "sampler_1",
    "sampler_2",
    "sampler_3",
    "sampler_4",
    "select",
    "atan2",
    "sample",
];

/// Godot built-ins that have no counterpart here.
pub(crate) const UNSUPPORTED_BUILTINS: &[&str] = &[
    "NORMAL",
    "NORMAL_MAP",
    "NORMAL_MAP_DEPTH",
    "NORMAL_TEXTURE",
    "SPECULAR_SHININESS",
    "SPECULAR_SHININESS_TEXTURE",
    "LIGHT",
    "LIGHT_COLOR",
    "LIGHT_POSITION",
    "LIGHT_DIRECTION",
    "LIGHT_ENERGY",
    "LIGHT_IS_DIRECTIONAL",
    "LIGHT_VERTEX",
    "SHADOW_VERTEX",
    "AT_LIGHT_PASS",
    "POINT_COORD",
    "POINT_SIZE",
    "CANVAS_MATRIX",
    "SCREEN_MATRIX",
    "INSTANCE_CUSTOM",
    "INSTANCE_ID",
    "VERTEX_ID",
    "CUSTOM0",
    "CUSTOM1",
    "REGION_RECT",
];

pub(crate) fn wgsl_type(ty: &str) -> Result<String> {
    Ok(match ty {
        "float" => "f32".into(),
        "int" => "i32".into(),
        "uint" => "u32".into(),
        "bool" => "bool".into(),
        "vec2" | "vec3" | "vec4" => format!("{ty}<f32>"),
        "ivec2" | "ivec3" | "ivec4" => format!("vec{}<i32>", &ty[4..]),
        "uvec2" | "uvec3" | "uvec4" => format!("vec{}<u32>", &ty[4..]),
        "bvec2" | "bvec3" | "bvec4" => format!("vec{}<bool>", &ty[4..]),
        "mat2" => "mat2x2<f32>".into(),
        "mat3" => "mat3x3<f32>".into(),
        "mat4" => "mat4x4<f32>".into(),
        other if other.starts_with("sampler") => bail!("a `{other}` outside a uniform"),
        other if TYPES.contains(&other) => bail!("the type `{other}` has no equivalent"),
        // A struct the shader declared.
        other => other.to_string(),
    })
}

pub(crate) fn sanitize(name: &str) -> String {
    let mut out = name.to_string();
    if out.starts_with("__") {
        out.insert(0, 'u');
    }
    if RESERVED.contains(&out.as_str()) {
        out.push('_');
    }
    out
}
